dataset_config:
  cvlg_coco2017:
    data_dir: ../mmf_cache/data/datasets
    use_images: True
    use_features: True
    # zoo_requirements:
    # - coco.defaults
    features:
      train:
      - coco/defaults/features/coco_train2017_ln.lmdb
      val:
      - coco/defaults/features/coco_val2017_ln.lmdb
      test:
      - coco/defaults/features/coco_val2017_ln.lmdb
    images:
      train:
      - coco/defaults/images/train2017
      # - /vc_data/users/t-kunyan/images/train2017
      val:
      - coco/defaults/images/val2017
      # - /vc_data/users/t-kunyan/images/val2017
      test:
      # - /vc_data/users/t-kunyan/images/val2017
      - coco/defaults/images/val2017
    annotations:
      train:
      - localized_narratives/defaults/annotations/coco_train_localized_narratives.lmdb
      val:
      - localized_narratives/defaults/annotations/coco_val_localized_narratives.lmdb
      test:
      - localized_narratives/defaults/annotations/coco_val_localized_narratives.lmdb
    processors:
      caption_processor:
        type: traced_bert_tokenizer
        params:
          tokenizer_config:
            type: bert-base-uncased
            params:
              do_lower_case: True
          max_seq_length: 64
      transformer_bbox_processor:
        type: transformer_bbox
        params:
          bbox_key: bbox
          image_width_key: image_width
          image_height_key: image_height
      trace_bbox_processor:
        type: spatial_trace_tokenizer
        params:
          max_seq_length: 256
          delta: 0.1
          reverse: false
          time_window: 0.1
      image_processor:
        type: torchvision_transforms
        params:
          transforms:
            - type: Resize
              params:
                size: [256, 256]
            - type: CenterCrop
              params:
                size: [256, 256]
            - ToTensor
            - GrayScaleTo3Channels
            # - type: Normalize
            #   params:
            #     mean: [0.46777044, 0.44531429, 0.40661017]
            #     std: [0.12221994, 0.12145835, 0.14380469]
